### ISSUE TITLE
trade price and amount has less precision than webapp value

### ISSUE THREAD

**Issue by jasan-s** [gateio/gateapi-nodejs#1] opened 2021-05-17 03:50 UTC
Using this Lib when i query my account trades , i have noticed the trade `amount` and `price`  retrieved value is less precise than the value viewable on the webapp.  i.e

Using webapp at `https://www.gate.io/myaccount/myhistory`  shows the following for a trade :

price: `0.000000022 `
amount: `16,132,646.41444999911`

Using `gateapi-nodejs` lib and calling `listMyTrades` function i receive the following:

price: `0.00000002`
amount: `16,132,646.41445`

The Issue:   Notice the `gateapi-nodejs` lib response has less digits after the decimal place 

How can i receive a more precise values.

**Comment by revilwang** [comment] 2021-05-17 03:53
Which method did you use to retrieve the result?

**Comment by revilwang** [comment] 2021-05-17 03:56
Hm, that's strange. The API result returns `string` type `amount`, which should contains all decimal places. Do you have additional handling of the `amount` field before print it out?

**Comment by jasan-s** [comment] 2021-05-17 04:01
No Im logging the raw response body. Its odd that the `gtFee` value  matches exactly with webapp value for the trade even though it has more digits after the decimal `gtFee: '0.0000477481206342'`

**Comment by revilwang** [comment] 2021-05-17 04:03
Please provide your uid and id if the trade.

**Comment by revilwang** [comment] 2021-05-17 04:04
Please provide your uid and id if the trade.

**Comment by jasan-s** [comment] 2021-05-17 04:06
trade_id: `1000647466`  uid: `5045861`

**Comment by revilwang** [comment] 2021-05-17 04:09
Okay, we'll check it later

**Comment by jasan-s** [comment] 2021-05-17 05:09
cool thanks. wondering if i use the Rest GET call directly if the values would differ.

**Comment by revilwang** [comment] 2021-05-17 05:12
You can try that. This SDK only parse the json response body and set fields with corresponding types. For string-typed fields, the value should be identical.

**Comment by revilwang** [comment] 2021-05-17 05:13
One more thing, can you please provide which currency pair this trade belongs to?

**Comment by jasan-s** [comment] 2021-05-17 05:14
you have an email i can send this to or jump on chat to share this info?

**Comment by revilwang** [comment] 2021-05-17 05:19
You can find my public email address in my github profile, but generally we recommend communicating using github issues, so that we may encounter some issues that may also affect others.

Thanks for the additional information. Currently no other information is needed. If you are concerned, you can send emails as you wish.

**Comment by jasan-s** [comment] 2021-05-17 05:23
I agree the discussion can def occur on github. but i sent you the trade related details to your email

**Comment by revilwang** [comment] 2021-05-17 05:38
There is a problem here. Thanks for reporting. 

I assume you call `listMyTrades` with `order_id` provided. Try omitting the parameter, and list all your trades by currency pair and pagination only. That result should be precise.

It is an issue of the server, we will try to solve it at a later time.

**Comment by jasan-s** [comment] 2021-05-17 05:59
thanks.  omitting `orderId`  `listMyTrades` does indeed returns more precise values. thanks. I'm assuming the bug lies in backend code thus when patch is deployed the issue would be resolved without requires updating lib version

**Comment by revilwang** [comment] 2021-05-17 06:01
Yes, it it the server's fault. No need to update the lib once the problem is fixed by the server.

**Comment by jasan-s** [comment] 2021-05-17 06:02
i'll leave the issue open , once fixed feel free to close the issue

**Comment by revilwang** [comment] 2021-05-18 10:34
Problem fixed. Previous trade precisions are not recovered, but future trade queries should return full precision

**Closed by revilwang** 2021-05-18 10:34 UTC
